# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tarea.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tarea.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0btarea.proto\"\x07\n\x05Vacio\"\x14\n\x04\x44\x61ta\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x10\n\x02ID\x12\n\n\x02id\x18\x01 \x01(\x05\"H\n\x07Mensaje\x12\x0e\n\x06id_ori\x18\x01 \x01(\x05\x12\x0e\n\x06id_des\x18\x02 \x01(\x05\x12\x0f\n\x07mensaje\x18\x03 \x01(\t\x12\x0c\n\x04time\x18\x04 \x01(\x02\x32\xab\x01\n\x05Tarea\x12!\n\rEnviarMensaje\x12\x08.Mensaje\x1a\x06.Vacio\x12\x1f\n\x0eRecibirMensaje\x12\x03.ID\x1a\x08.Mensaje\x12 \n\x0fObtenerUsuarios\x12\x06.Vacio\x1a\x05.Data\x12\x1d\n\x0e\x41gregarUsuario\x12\x06.Vacio\x1a\x03.ID\x12\x1d\n\x0fObtenerMensajes\x12\x03.ID\x1a\x05.Datab\x06proto3')
)




_VACIO = _descriptor.Descriptor(
  name='Vacio',
  full_name='Vacio',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=22,
)


_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='Data.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=44,
)


_ID = _descriptor.Descriptor(
  name='ID',
  full_name='ID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ID.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=62,
)


_MENSAJE = _descriptor.Descriptor(
  name='Mensaje',
  full_name='Mensaje',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_ori', full_name='Mensaje.id_ori', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id_des', full_name='Mensaje.id_des', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mensaje', full_name='Mensaje.mensaje', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='Mensaje.time', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=136,
)

DESCRIPTOR.message_types_by_name['Vacio'] = _VACIO
DESCRIPTOR.message_types_by_name['Data'] = _DATA
DESCRIPTOR.message_types_by_name['ID'] = _ID
DESCRIPTOR.message_types_by_name['Mensaje'] = _MENSAJE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vacio = _reflection.GeneratedProtocolMessageType('Vacio', (_message.Message,), {
  'DESCRIPTOR' : _VACIO,
  '__module__' : 'tarea_pb2'
  # @@protoc_insertion_point(class_scope:Vacio)
  })
_sym_db.RegisterMessage(Vacio)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
  'DESCRIPTOR' : _DATA,
  '__module__' : 'tarea_pb2'
  # @@protoc_insertion_point(class_scope:Data)
  })
_sym_db.RegisterMessage(Data)

ID = _reflection.GeneratedProtocolMessageType('ID', (_message.Message,), {
  'DESCRIPTOR' : _ID,
  '__module__' : 'tarea_pb2'
  # @@protoc_insertion_point(class_scope:ID)
  })
_sym_db.RegisterMessage(ID)

Mensaje = _reflection.GeneratedProtocolMessageType('Mensaje', (_message.Message,), {
  'DESCRIPTOR' : _MENSAJE,
  '__module__' : 'tarea_pb2'
  # @@protoc_insertion_point(class_scope:Mensaje)
  })
_sym_db.RegisterMessage(Mensaje)



_TAREA = _descriptor.ServiceDescriptor(
  name='Tarea',
  full_name='Tarea',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=139,
  serialized_end=310,
  methods=[
  _descriptor.MethodDescriptor(
    name='EnviarMensaje',
    full_name='Tarea.EnviarMensaje',
    index=0,
    containing_service=None,
    input_type=_MENSAJE,
    output_type=_VACIO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RecibirMensaje',
    full_name='Tarea.RecibirMensaje',
    index=1,
    containing_service=None,
    input_type=_ID,
    output_type=_MENSAJE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ObtenerUsuarios',
    full_name='Tarea.ObtenerUsuarios',
    index=2,
    containing_service=None,
    input_type=_VACIO,
    output_type=_DATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AgregarUsuario',
    full_name='Tarea.AgregarUsuario',
    index=3,
    containing_service=None,
    input_type=_VACIO,
    output_type=_ID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ObtenerMensajes',
    full_name='Tarea.ObtenerMensajes',
    index=4,
    containing_service=None,
    input_type=_ID,
    output_type=_DATA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TAREA)

DESCRIPTOR.services_by_name['Tarea'] = _TAREA

# @@protoc_insertion_point(module_scope)
