version: '3'

services:
  rabbitmq:
    image: 'rabbitmq:latest'
    hostname: 'rabbit'
    ports: 
      - '5000:6000'
      - '15672:15672'
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
  server:
    build: ./
    command: python ./server.py
    depends_on:
      - rabbitmq
    network_mode: host
    tty: true
  client:
    build: ./
    command: python ./client.py
    depends_on:
      - rabbitmq
    network_mode: host
    stdin_open: true
    tty: true